server_host: "0.0.0.0"
server_port: 8889
ldap_config:
  server: your-ldap.example.org:389
  authenticated: true
  unsecured: false
  bind_dn: "CN=ro_user,OU=Service Accounts,DC=example,DC=org"
  base_dn_mappings:
    desktops:
      base_dn_list:
      - "OU=Computers,OU=Office 1,DC=sqpc,DC=sqrpnt,DC=com"
      - "OU=Computers,OU=Office 2,OU=Office,DC=example,DC=org"
      exporter_port: 5000
      attributes:
      - canonicalName
      - userAccountControl
      - location
    servers:
      base_dn_list:
      - "OU=Datacenter 1,OU=Servers,DC=example,DC=org"
      - "OU=Datacenter 2,OU=Servers,DC=example,DC=org"
      exporter_port: 5000
      filter: "(&(objectClass=computer))"
  group_exporter_port_mapping:
    desktops: 5000
    servers: 5000
  #filter: "" # default is always (&(objectClass=computer))
  default_attributes: # by default, the follow attributes are automatically fetched: name, dNSHostName
    - operatingSystem
  cache_dir: cache
  cache_ttl: 60
  password_env_var: AD_AUTH_PASS